/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "myetfeidselcbobpcmok"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15ZXRmZWlkc2VsY2JvYnBjbW9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNzYwMzgsImV4cCI6MjA4MDk1MjAzOH0.-WcgN-SG3ElWDVITnNIztZwXw1kjETAxOIcZatTwLZU"